### ISSUE TITLE
Using helm to spin up Phenomenal

### ISSUE THREAD

**Issue by deepBiomeDiego** [phnmnl/helm-charts#10]
Hello I just attempted to use this helm chart to spin up the phenomenal portal to great success! But I think this is only spinning up the portal not the galaxy instance, I was wondering, is there a helm chart to do that yet? or is it under active development?

**Comment by sneumann** [comment]
Hi, check the README here, you'll find the charts in https://github.com/galaxyproject/galaxy-kubernetes.
In Phnmnl they are installed via ansible from here: https://github.com/phnmnl/KubeNow-plugin/blob/master/playbooks/roles/galaxy/tasks/main.yml 
Hope that helped, yours, Steffen

**Comment by deepBiomeDiego** [comment]
Really super helpful!
Not sure if i'm doing this right, but when I cd into my-vre-config-dir after running "kn --preset phenomenal init gce my-vre-config-dir"
 the directory seems to be empty? I added a config.tfvars file but i assumed it should've been created automatically, is this right?
Also after i spin up the phenomenal portal using:
kn apply
Do i need to separately spin up the galaxy chart as well?

--Thank you

**Comment by sneumann** [comment]
Hi, glad to be helpful. In your `my-vre-config-dir` you should see 
```
sneumann@msbi-corei:/vol/phenomenal/kubenow$ kn --preset phenomenal init gce my-vre-config-dir
Setting preset: phenomenal
Using provisioner version: kubenow/provisioners:phenomenal-stable
Clone plugin repo: https://github.com/phnmnl/KubeNow-plugin.git
...
Clone plugin repo done
Using plugin configuration: phnmnl/KubeNow-plugin
Initializing deployment directory for cloud provider gce
Generating public/private rsa key pair.
...
# Deploy cluster
kn apply

sneumann@msbi-corei:/vol/phenomenal/kubenow$ ls my-vre-config-dir/
ansible.cfg  bin  bootstrap  common  config.tfvars  gce  inventory-template  playbooks  plugins  ssh_key  ssh_key.pub
```
Then, if you `kn apply` it will first terraform your VMs and stuff, and then use ansible inside to install k8s and finally it will helm all the services enabled in your config.tfvars, including Galaxy. 
If you still have issues with `kn init`, feel free to post an issue in https://github.com/phnmnl/KubeNow-plugin
Yours, Steffen

**Comment by sneumann** [comment]
I guess this issue can be closed now, feel free to open new ones if you bump into other issues. And Thanks for trying PhenoMeNal ! Yours, Steffen
